### ISSUE TITLE
How to map tmux default keymap to change windows?

### ISSUE THREAD

**Issue by alexcamlo** [yurikhan/kitty-smart-tab#1]
By default, in Tmux to change between windows the shortcut is c-b (c-a in my case) + number.
How can I map this? I tried

`map cmd+1 kitten smart_tab.py goto_tab 1  ctrl+a>1`

But it gives me:

`kitten smart_tab.py goto_tab 1 ctrl+a>1
ord() expected a character, but string of length 3 found`

**Comment by yurikhan** [comment]
I’m afraid I don’t currently support emitting a sequence. Patches welcome.

**Comment by alexcamlo** [comment]
So how do you do to change windows in tmux with alt+number?

**Comment by yurikhan** [comment]
I bound them in my tmux.conf with `bind-key -n`, of course.
